GET http://localhost:3001/api/notes
###

GET http://localhost:3001/api/notes/63ae1d6be544ac5de89cf4101
###

POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "Test",
    "important": false
}

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "",
    "important": false
}

###
DELETE http://localhost:3001/api/notes/63c514b068b3ce880e54b08a

###
post http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "hello",
    "password": "hello"
}

###
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "hello",
    "password": "hello"
}